version: '3.1'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  fluentd:
    image: fluent/fluentd
    ports:
      - "24224:24224"
  fdns-ms-stubbing:
    image: cdcgov/fdns-ms-stubbing
    ports:
      - "3002:3002"